export const countries = [
  { code: 'BR', name: 'Brasil' },
  { code: 'AR', name: 'Argentina' },
  { code: 'BO', name: 'Bolívia' },
  { code: 'CL', name: 'Chile' },
  { code: 'CO', name: 'Colômbia' },
  { code: 'EC', name: 'Equador' },
  { code: 'FK', name: 'Ilhas Malvinas' },
  { code: 'GF', name: 'Guiana Francesa' },
  { code: 'GY', name: 'Guiana' },
  { code: 'PY', name: 'Paraguai' },
  { code: 'PE', name: 'Peru' },
  { code: 'SR', name: 'Suriname' },
  { code: 'UY', name: 'Uruguai' },
  { code: 'VE', name: 'Venezuela' },
  { code: 'US', name: 'Estados Unidos' },
  { code: 'CA', name: 'Canadá' },
  { code: 'MX', name: 'México' },
  { code: 'GB', name: 'Reino Unido' },
  { code: 'FR', name: 'França' },
  { code: 'DE', name: 'Alemanha' },
  { code: 'IT', name: 'Itália' },
  { code: 'ES', name: 'Espanha' },
  { code: 'PT', name: 'Portugal' },
  { code: 'NL', name: 'Holanda' },
  { code: 'BE', name: 'Bélgica' },
  { code: 'CH', name: 'Suíça' },
  { code: 'AT', name: 'Áustria' },
  { code: 'SE', name: 'Suécia' },
  { code: 'NO', name: 'Noruega' },
  { code: 'DK', name: 'Dinamarca' },
  { code: 'FI', name: 'Finlândia' },
  { code: 'PL', name: 'Polônia' },
  { code: 'CZ', name: 'República Tcheca' },
  { code: 'HU', name: 'Hungria' },
  { code: 'RO', name: 'Romênia' },
  { code: 'BG', name: 'Bulgária' },
  { code: 'HR', name: 'Croácia' },
  { code: 'RS', name: 'Sérvia' },
  { code: 'SI', name: 'Eslovênia' },
  { code: 'SK', name: 'Eslováquia' },
  { code: 'LT', name: 'Lituânia' },
  { code: 'LV', name: 'Letônia' },
  { code: 'EE', name: 'Estônia' },
  { code: 'IE', name: 'Irlanda' },
  { code: 'IS', name: 'Islândia' },
  { code: 'LU', name: 'Luxemburgo' },
  { code: 'MT', name: 'Malta' },
  { code: 'CY', name: 'Chipre' },
  { code: 'GR', name: 'Grécia' },
  { code: 'TR', name: 'Turquia' },
  { code: 'RU', name: 'Rússia' },
  { code: 'UA', name: 'Ucrânia' },
  { code: 'BY', name: 'Bielorrússia' },
  { code: 'MD', name: 'Moldávia' },
  { code: 'GE', name: 'Geórgia' },
  { code: 'AM', name: 'Armênia' },
  { code: 'AZ', name: 'Azerbaijão' },
  { code: 'KZ', name: 'Cazaquistão' },
  { code: 'UZ', name: 'Uzbequistão' },
  { code: 'TM', name: 'Turcomenistão' },
  { code: 'TJ', name: 'Tajiquistão' },
  { code: 'KG', name: 'Quirguistão' },
  { code: 'AF', name: 'Afeganistão' },
  { code: 'PK', name: 'Paquistão' },
  { code: 'IN', name: 'Índia' },
  { code: 'BD', name: 'Bangladesh' },
  { code: 'LK', name: 'Sri Lanka' },
  { code: 'MV', name: 'Maldivas' },
  { code: 'BT', name: 'Butão' },
  { code: 'NP', name: 'Nepal' },
  { code: 'CN', name: 'China' },
  { code: 'MN', name: 'Mongólia' },
  { code: 'KP', name: 'Coreia do Norte' },
  { code: 'KR', name: 'Coreia do Sul' },
  { code: 'JP', name: 'Japão' },
  { code: 'TW', name: 'Taiwan' },
  { code: 'HK', name: 'Hong Kong' },
  { code: 'MO', name: 'Macau' },
  { code: 'TH', name: 'Tailândia' },
  { code: 'LA', name: 'Laos' },
  { code: 'KH', name: 'Camboja' },
  { code: 'VN', name: 'Vietnã' },
  { code: 'MY', name: 'Malásia' },
  { code: 'SG', name: 'Singapura' },
  { code: 'ID', name: 'Indonésia' },
  { code: 'PH', name: 'Filipinas' },
  { code: 'BN', name: 'Brunei' },
  { code: 'MM', name: 'Myanmar' },
  { code: 'AU', name: 'Austrália' },
  { code: 'NZ', name: 'Nova Zelândia' },
  { code: 'FJ', name: 'Fiji' },
  { code: 'PG', name: 'Papua Nova Guiné' },
  { code: 'SB', name: 'Ilhas Salomão' },
  { code: 'VU', name: 'Vanuatu' },
  { code: 'NC', name: 'Nova Caledônia' },
  { code: 'PF', name: 'Polinésia Francesa' },
  { code: 'WS', name: 'Samoa' },
  { code: 'TO', name: 'Tonga' },
  { code: 'KI', name: 'Kiribati' },
  { code: 'TV', name: 'Tuvalu' },
  { code: 'NR', name: 'Nauru' },
  { code: 'PW', name: 'Palau' },
  { code: 'FM', name: 'Micronésia' },
  { code: 'MH', name: 'Ilhas Marshall' },
  { code: 'ZA', name: 'África do Sul' },
  { code: 'EG', name: 'Egito' },
  { code: 'LY', name: 'Líbia' },
  { code: 'TN', name: 'Tunísia' },
  { code: 'DZ', name: 'Argélia' },
  { code: 'MA', name: 'Marrocos' },
  { code: 'SD', name: 'Sudão' },
  { code: 'SS', name: 'Sudão do Sul' },
  { code: 'ET', name: 'Etiópia' },
  { code: 'ER', name: 'Eritreia' },
  { code: 'DJ', name: 'Djibuti' },
  { code: 'SO', name: 'Somália' },
  { code: 'KE', name: 'Quênia' },
  { code: 'UG', name: 'Uganda' },
  { code: 'TZ', name: 'Tanzânia' },
  { code: 'RW', name: 'Ruanda' },
  { code: 'BI', name: 'Burundi' },
  { code: 'CD', name: 'República Democrática do Congo' },
  { code: 'CG', name: 'República do Congo' },
  { code: 'CF', name: 'República Centro-Africana' },
  { code: 'CM', name: 'Camarões' },
  { code: 'TD', name: 'Chade' },
  { code: 'NE', name: 'Níger' },
  { code: 'NG', name: 'Nigéria' },
  { code: 'BJ', name: 'Benin' },
  { code: 'TG', name: 'Togo' },
  { code: 'GH', name: 'Gana' },
  { code: 'BF', name: 'Burkina Faso' },
  { code: 'ML', name: 'Mali' },
  { code: 'SN', name: 'Senegal' },
  { code: 'GM', name: 'Gâmbia' },
  { code: 'GN', name: 'Guiné' },
  { code: 'GW', name: 'Guiné-Bissau' },
  { code: 'SL', name: 'Serra Leoa' },
  { code: 'LR', name: 'Libéria' },
  { code: 'CI', name: 'Costa do Marfim' },
  { code: 'GH', name: 'Gana' },
  { code: 'TG', name: 'Togo' },
  { code: 'BJ', name: 'Benin' },
  { code: 'NG', name: 'Nigéria' },
  { code: 'NE', name: 'Níger' },
  { code: 'TD', name: 'Chade' },
  { code: 'CM', name: 'Camarões' },
  { code: 'CF', name: 'República Centro-Africana' },
  { code: 'CG', name: 'República do Congo' },
  { code: 'CD', name: 'República Democrática do Congo' },
  { code: 'AO', name: 'Angola' },
  { code: 'ZM', name: 'Zâmbia' },
  { code: 'ZW', name: 'Zimbábue' },
  { code: 'BW', name: 'Botswana' },
  { code: 'NA', name: 'Namíbia' },
  { code: 'SZ', name: 'Eswatini' },
  { code: 'LS', name: 'Lesoto' },
  { code: 'MG', name: 'Madagascar' },
  { code: 'MU', name: 'Maurício' },
  { code: 'SC', name: 'Seicheles' },
  { code: 'KM', name: 'Comores' },
  { code: 'YT', name: 'Mayotte' },
  { code: 'RE', name: 'Reunião' },
  { code: 'MZ', name: 'Moçambique' },
  { code: 'MW', name: 'Malawi' },
  { code: 'ZM', name: 'Zâmbia' },
  { code: 'ZW', name: 'Zimbábue' },
  { code: 'BW', name: 'Botswana' },
  { code: 'NA', name: 'Namíbia' },
  { code: 'SZ', name: 'Eswatini' },
  { code: 'LS', name: 'Lesoto' },
  { code: 'MG', name: 'Madagascar' },
  { code: 'MU', name: 'Maurício' },
  { code: 'SC', name: 'Seicheles' },
  { code: 'KM', name: 'Comores' },
  { code: 'YT', name: 'Mayotte' },
  { code: 'RE', name: 'Reunião' },
  { code: 'MZ', name: 'Moçambique' },
  { code: 'MW', name: 'Malawi' }
];
